AWSTemplateFormatVersion: 2010-09-09
Description: >
  REQUIREMENT: Obtain Your Domain Name
  Route53 HostedZone Creation & You need to set up Nameservers after deploying
Parameters:
  DomainName: 
    Type: String

Resources: 
  DomainNameHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Sub ${DomainName}

Outputs:
  HostedZoneId:
    Description: HostedZoneId for HostedZone in Route53
    Value: !Ref DomainNameHostedZone
    Export: 
      Name: !Sub "${AWS::StackName}-HostedZoneId"
