AWSTemplateFormatVersion: 2010-09-09
Description: >
  This is Route53RecordSet Template for Website Set
Parameters:
  HostedZoneId:
    Type: String
    Description: Amazon Route 53 hostedzoneId which you created in advanced

  DomainName:
    Type: String
    Description: The domain name for your website in Route53
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name pattern
  
  CfDomainName:
    Type: String
    Description: This value comes from CfDistribution Stack

Resources:
  WebsiteDNSName:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Sub "www.${DomainName}"
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !Ref CfDomainName
